"""Add table column preferences

Revision ID: 2dda66e39a63
Revises: 9b326cbd41dc
Create Date: 2025-01-14 00:19:07.022607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dda66e39a63'
down_revision = '9b326cbd41dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_column_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_type', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('uix_table_column', type_='unique')
        batch_op.create_unique_constraint('unique_column_per_table', ['table_type', 'column_name'])
        batch_op.drop_column('icon')
        batch_op.drop_column('table_name')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_column_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint('unique_column_per_table', type_='unique')
        batch_op.create_unique_constraint('uix_table_column', ['table_name', 'column_name'])
        batch_op.drop_column('table_type')

    # ### end Alembic commands ###
