"""Add currency column to expense table

Revision ID: 607baf2e990b
Revises: 
Create Date: 2025-03-04 13:15:28.846645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607baf2e990b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default='ILS', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
