"""Add credit card model and relationships

Revision ID: 9b326cbd41dc
Revises: 
Create Date: 2025-01-01 22:42:13.511597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b326cbd41dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'credit_card', ['credit_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('credit_card_id')

    # ### end Alembic commands ###
