'''add_new_frontend_column_to_user

Revision ID: add_new_frontend_20251123
Revises: None
Create Date: 2025-11-23 00:20:00.000000
'''

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_new_frontend_20251123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_frontend', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_frontend')
    # ### end Alembic commands ###
