"""add bank details to supplier

Revision ID: cb8f062e461a
Revises: eed33f2e4096
Create Date: 2024-12-29 10:33:36.277032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8f062e461a'
down_revision = 'eed33f2e4096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_swift', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('bank_swift')
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
